CREATE TABLE USER(
   ID SERIAL PRIMARY KEY NOT NULL,
   NAME VARCHAR(255) NOT NULL,
   EMAIL VARCHAR(255) NOT NULL,
   PASSWORD VARCHAR(255) NOT NULL,
	 ROLE SMALLINT NOT NULL
);

CREATE TABLE CURSO(
   ID SERIAL PRIMARY KEY NOT NULL,
   NAME VARCHAR(255) NOT NULL
);

CREATE TABLE PROFESOR_CURSO(
   ID SERIAL PRIMARY KEY NOT NULL,
   USER_ID INT NOT NULL,
   CURSO_ID INT NOT NULL
);

CREATE TABLE ALUMNO_CURSO(
   ID SERIAL PRIMARY KEY NOT NULL,
   USER_ID INT NOT NULL,
   CURSO_ID INT NOT NULL,
	 NOTA_FINAL DECIMAL(3,2),
	 ESTADO VARCHAR(255)
);

CREATE TABLE NOTAS(
   ID SERIAL PRIMARY KEY NOT NULL,
   USER_ID INT NOT NULL,
   CURSO_ID INT NOT NULL,
   NOTA DECIMAL(3,2) NOT NULL
);